/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firmdemo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAYEM
 */
public class DeleteForm extends javax.swing.JFrame {

    Connection linkwithdatabase;
    PreparedStatement prestat;
    DefaultTableModel model;
    Object[] data;
    ResultSet rs;
    int recentydelete;
    /**
     * Creates new form DeshBoard
     */
    public DeleteForm() {
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("cow no");
        model.addColumn("Stall");
        model.addColumn("Price");
        model.addColumn("Gender");
        model.addColumn("Height");
        model.addColumn("Weight");
        model.addColumn("type");
        model.addColumn("Dob Month");
        model.addColumn("Dob Month");
        model.addColumn("Description");
        model.addColumn("Supplier");
        model.addColumn("Month");
        model.addColumn("year");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//not close all window
        showdata();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buycowform = new javax.swing.JPanel();
        deshlabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deshboardpart = new javax.swing.JPanel();
        deshlabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sellpart = new javax.swing.JPanel();
        deshlabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updatepart = new javax.swing.JPanel();
        deshlabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cowinformation = new javax.swing.JPanel();
        deshlabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        employeespart = new javax.swing.JPanel();
        deshlabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        deletepart = new javax.swing.JPanel();
        deshlabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showdata = new javax.swing.JTable();
        todaydate = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        cownumber = new javax.swing.JTextField();
        showallbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\profile.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Rizvi Ahmed");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("active");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\active.png")); // NOI18N
        jLabel4.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        buycowform.setBackground(new java.awt.Color(255, 255, 255));
        buycowform.setForeground(new java.awt.Color(0, 0, 0));
        buycowform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buycowformMouseClicked(evt);
            }
        });

        deshlabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel.setText("Buy");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\cowicon.jpg")); // NOI18N
        jLabel5.setText(" ");

        javax.swing.GroupLayout buycowformLayout = new javax.swing.GroupLayout(buycowform);
        buycowform.setLayout(buycowformLayout);
        buycowformLayout.setHorizontalGroup(
            buycowformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buycowformLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buycowformLayout.setVerticalGroup(
            buycowformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buycowformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buycowformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deshboardpart.setBackground(new java.awt.Color(255, 255, 255));
        deshboardpart.setForeground(new java.awt.Color(0, 0, 0));
        deshboardpart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshboardpartMouseClicked(evt);
            }
        });

        deshlabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel1.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel1.setText("Dashboard");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\deshboard.png")); // NOI18N
        jLabel6.setText(" ");

        javax.swing.GroupLayout deshboardpartLayout = new javax.swing.GroupLayout(deshboardpart);
        deshboardpart.setLayout(deshboardpartLayout);
        deshboardpartLayout.setHorizontalGroup(
            deshboardpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshboardpartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deshboardpartLayout.setVerticalGroup(
            deshboardpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deshboardpartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deshboardpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel1)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sellpart.setBackground(new java.awt.Color(255, 255, 255));
        sellpart.setForeground(new java.awt.Color(0, 0, 0));
        sellpart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellpartMouseClicked(evt);
            }
        });

        deshlabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel2.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel2.setText("Sell");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\sell.jpg")); // NOI18N
        jLabel7.setText(" ");

        javax.swing.GroupLayout sellpartLayout = new javax.swing.GroupLayout(sellpart);
        sellpart.setLayout(sellpartLayout);
        sellpartLayout.setHorizontalGroup(
            sellpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellpartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sellpartLayout.setVerticalGroup(
            sellpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellpartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel2)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatepart.setBackground(new java.awt.Color(255, 255, 255));
        updatepart.setForeground(new java.awt.Color(0, 0, 0));
        updatepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatepartMouseClicked(evt);
            }
        });

        deshlabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel4.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel4.setText("Update");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\updateion.png")); // NOI18N
        jLabel9.setText(" ");

        javax.swing.GroupLayout updatepartLayout = new javax.swing.GroupLayout(updatepart);
        updatepart.setLayout(updatepartLayout);
        updatepartLayout.setHorizontalGroup(
            updatepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel4)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        updatepartLayout.setVerticalGroup(
            updatepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel4)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cowinformation.setBackground(new java.awt.Color(255, 255, 255));
        cowinformation.setForeground(new java.awt.Color(0, 0, 0));
        cowinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cowinformationMouseClicked(evt);
            }
        });

        deshlabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel5.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel5.setText("Cow Information");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\buyicon.png")); // NOI18N
        jLabel10.setText(" ");

        javax.swing.GroupLayout cowinformationLayout = new javax.swing.GroupLayout(cowinformation);
        cowinformation.setLayout(cowinformationLayout);
        cowinformationLayout.setHorizontalGroup(
            cowinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cowinformationLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cowinformationLayout.setVerticalGroup(
            cowinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cowinformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cowinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel5)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeespart.setBackground(new java.awt.Color(255, 255, 255));
        employeespart.setForeground(new java.awt.Color(0, 0, 0));
        employeespart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeespartMouseClicked(evt);
            }
        });

        deshlabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel6.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel6.setText("Employees");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\employeeicon.jpg")); // NOI18N
        jLabel11.setText(" ");

        javax.swing.GroupLayout employeespartLayout = new javax.swing.GroupLayout(employeespart);
        employeespart.setLayout(employeespartLayout);
        employeespartLayout.setHorizontalGroup(
            employeespartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeespartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeespartLayout.setVerticalGroup(
            employeespartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeespartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeespartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel6)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deletepart.setBackground(new java.awt.Color(255, 255, 255));
        deletepart.setForeground(new java.awt.Color(0, 0, 0));
        deletepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletepartMouseClicked(evt);
            }
        });

        deshlabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel3.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel3.setText("Delete");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\deleteicon.jpg")); // NOI18N
        jLabel8.setText(" ");

        javax.swing.GroupLayout deletepartLayout = new javax.swing.GroupLayout(deletepart);
        deletepart.setLayout(deletepartLayout);
        deletepartLayout.setHorizontalGroup(
            deletepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletepartLayout.setVerticalGroup(
            deletepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel3)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deshboardpart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buycowform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sellpart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cowinformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updatepart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(employeespart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshboardpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buycowform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cowinformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatepart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletepart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeespart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COW FIRM LOGO");

        logoutbtn.setBackground(new java.awt.Color(51, 153, 255));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Log Out");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\logouticon.png")); // NOI18N
        jLabel27.setText(" ");

        javax.swing.GroupLayout logoutbtnLayout = new javax.swing.GroupLayout(logoutbtn);
        logoutbtn.setLayout(logoutbtnLayout);
        logoutbtnLayout.setHorizontalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutbtnLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        logoutbtnLayout.setVerticalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel26.setText("Delete Cow Information");

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1377, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        showdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        showdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(showdata);

        todaydate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        todaydate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        deletebtn.setBackground(new java.awt.Color(51, 153, 255));
        deletebtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        showallbtn.setBackground(new java.awt.Color(51, 153, 255));
        showallbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        showallbtn.setForeground(new java.awt.Color(255, 255, 255));
        showallbtn.setText("Show all Data");
        showallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(todaydate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(cownumber, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showallbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(todaydate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cownumber, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showallbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buycowformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buycowformMouseClicked
        dispose();
        new buyform().setVisible(true);
    }//GEN-LAST:event_buycowformMouseClicked
    public void showdata() {
        try {
            linkwithdatabase = DriverManager.getConnection("jdbc:mysql://localhost:3306/cow_firm_project", "root", "nh12345");
            prestat = linkwithdatabase.prepareStatement("select * from cowbuy_table");

            rs = prestat.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                data = new Object[]{rs.getInt(1), rs.getString(2), rs.getDouble(3), rs.getString(4), rs.getDouble(5), rs.getDouble(6), rs.getString(7),
                    rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13)

                };
                model.addRow(data);
                showdata.setModel(model);
            }
        } catch (Exception e) {
        }
    }
    private void deshboardpartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshboardpartMouseClicked
        dispose();
        new DeshBoard().setVisible(true);
    }//GEN-LAST:event_deshboardpartMouseClicked

    private void sellpartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellpartMouseClicked
        dispose();
        new sellform().setVisible(true);
    }//GEN-LAST:event_sellpartMouseClicked

    private void deletepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deletepartMouseClicked

    private void updatepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepartMouseClicked
        dispose();
        new Updateform().setVisible(true);
    }//GEN-LAST:event_updatepartMouseClicked

    private void cowinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cowinformationMouseClicked
        dispose();
        new cowinformation().setVisible(true);
    }//GEN-LAST:event_cowinformationMouseClicked

    private void employeespartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeespartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employeespartMouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        dispose();
        new LogIN().setVisible(true);
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        deletepart();


    }//GEN-LAST:event_deletebtnActionPerformed
public void deletepart(){
    try {

            linkwithdatabase = DriverManager.getConnection("jdbc:mysql://localhost:3306/cow_firm_project", "root", "nh12345");
            prestat = linkwithdatabase.prepareStatement("delete from cowbuy_table where cow_number=?");
            prestat.setInt(1, Integer.parseInt(cownumber.getText()));
            recentydelete = Integer.parseInt(cownumber.getText());
            int n = prestat.executeUpdate();
            if (n > 0) {
                System.out.println("delete done");
            } else {
                System.out.println("Data doesnot delete");
            }
        } catch (Exception e) {
        } finally {
            try {
                linkwithdatabase.close();
                prestat.close();
            } catch (Exception e) {
            }
        }
}
    private void showallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallbtnActionPerformed
        showdata();
    }//GEN-LAST:event_showallbtnActionPerformed

    private void showdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showdataMouseClicked
        cownumber.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 0)));
    }//GEN-LAST:event_showdataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buycowform;
    private javax.swing.JPanel cowinformation;
    private javax.swing.JTextField cownumber;
    private javax.swing.JButton deletebtn;
    private javax.swing.JPanel deletepart;
    private javax.swing.JPanel deshboardpart;
    private javax.swing.JLabel deshlabel;
    private javax.swing.JLabel deshlabel1;
    private javax.swing.JLabel deshlabel2;
    private javax.swing.JLabel deshlabel3;
    private javax.swing.JLabel deshlabel4;
    private javax.swing.JLabel deshlabel5;
    private javax.swing.JLabel deshlabel6;
    private javax.swing.JPanel employeespart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JPanel sellpart;
    private javax.swing.JButton showallbtn;
    private javax.swing.JTable showdata;
    private javax.swing.JLabel todaydate;
    private javax.swing.JPanel updatepart;
    // End of variables declaration//GEN-END:variables
}
