/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firmdemo;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SAYEM
 */
public class RegistationForm extends javax.swing.JFrame {

    Connection linkwithdatabase;
    PreparedStatement prestat;

    /**
     * Creates new form RegistationForm
     */
    public RegistationForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//not close all window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailfeild = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namefeild = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setpassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JTextField();
        createaccountbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        codeforcreate = new javax.swing.JTextField();
        namelabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        passlabel1 = new javax.swing.JLabel();
        codelabel = new javax.swing.JLabel();
        passmatchlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registation form");

        emailfeild.setText("example_.06@gmail.com");
        emailfeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfeildFocusLost(evt);
            }
        });

        jLabel2.setText("Email");

        namefeild.setText("Name");
        namefeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namefeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namefeildFocusLost(evt);
            }
        });
        namefeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefeildActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Password");

        setpassword.setText("Password");
        setpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                setpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                setpasswordFocusLost(evt);
            }
        });

        jLabel5.setText("Confirm Password");

        confirmpassword.setText("Password");
        confirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmpasswordFocusLost(evt);
            }
        });

        createaccountbtn.setBackground(new java.awt.Color(51, 153, 255));
        createaccountbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        createaccountbtn.setForeground(new java.awt.Color(255, 255, 255));
        createaccountbtn.setText("Create Account");
        createaccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccountbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirmation code (Given by Admin)");

        codeforcreate.setText("code");
        codeforcreate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codeforcreateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeforcreateFocusLost(evt);
            }
        });

        namelabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        namelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namelabel.setText(" ");

        emaillabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        emaillabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emaillabel.setText(" ");

        passlabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passlabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        codelabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        codelabel.setText(" ");

        passmatchlabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(createaccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(emailfeild)
                            .addComponent(namefeild, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(setpassword)
                            .addComponent(confirmpassword)
                            .addComponent(codeforcreate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emaillabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passlabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passmatchlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namefeild, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passmatchlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeforcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(codelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(createaccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefeildActionPerformed

    private void createaccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccountbtnActionPerformed
        Pattern email = Pattern.compile("^[a-z0-9._]+\\@[a-z0-9]+\\.[a-z]{2,5}$");
        Pattern passpatt = Pattern.compile("^[a-z0-9]{8,20}$");
        if (namefeild.getText().equals("Name")) {
            namelabel.setText("Enter your Name");
            namelabel.setForeground(Color.red);
        } else {
            namelabel.setText(null);
            namelabel.setForeground(null);
        }
        if (emailfeild.getText().equals("example_.06@gmail.com") || !email.matcher(emailfeild.getText()).matches()) {
            emaillabel.setText("Enter your email");
            emaillabel.setForeground(Color.red);
        } else {
            emaillabel.setText(null);
            emaillabel.setForeground(null);
        }
        if (setpassword.getText().equals("Password")) {
            passlabel1.setText("Enter your password");
            passlabel1.setForeground(Color.red);
        } else {
            passlabel1.setText(null);
            passlabel1.setForeground(null);
        }

        if (passpatt.matcher(setpassword.getText()).matches()) {
            passlabel1.setText(null);
            passlabel1.setForeground(null);
        } else {
            passlabel1.setText("password will be 8-20 digit");
            passlabel1.setForeground(Color.red);
        }

        if (setpassword.getText().equals(confirmpassword.getText())) {
            passmatchlabel.setText(null);
            passmatchlabel.setForeground(null);
        } else {
            passmatchlabel.setText("Doesnot Match Password");
            passmatchlabel.setForeground(Color.red);
        }
        if (codeforcreate.getText().equals("code")) {
            codeforcreate.setForeground(Color.red);
            codelabel.setText("wrong code");
            codelabel.setForeground(Color.red);
        } else {
            codelabel.setText(null);
            codelabel.setForeground(null);
        }
        if (codeforcreate.getText().equals("1205")) {
            codeforcreate.setForeground(Color.green);
        } else {

        }
        if (email.matcher(emailfeild.getText()).matches() && codeforcreate.getText().equals("1205") && passpatt.matcher(setpassword.getText()).matches() && confirmpassword.getText().equals(setpassword.getText())
                && !emailfeild.getText().equals("example_.06@gmail.com") && !namefeild.getText().equals("Name") && !setpassword.getText().equals("Password")) {
            insertuserdata();
            JOptionPane.showMessageDialog(null, "insert data");
        }


    }//GEN-LAST:event_createaccountbtnActionPerformed

    private void namefeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefeildFocusGained
        if (namefeild.getText().equals("Name")) {
            namefeild.setText("");
        }
    }//GEN-LAST:event_namefeildFocusGained

    private void emailfeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfeildFocusGained
        if (emailfeild.getText().equals("example_.06@gmail.com")) {
            emailfeild.setText("");
        }
    }//GEN-LAST:event_emailfeildFocusGained

    private void namefeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefeildFocusLost
        if (namefeild.getText().equals("")) {
            namefeild.setText("Name");
        }
    }//GEN-LAST:event_namefeildFocusLost

    private void emailfeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfeildFocusLost
        if (emailfeild.getText().equals("")) {
            emailfeild.setText("example_.06@gmail.com");
        }
    }//GEN-LAST:event_emailfeildFocusLost

    private void setpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_setpasswordFocusGained
        if (setpassword.getText().equals("Password")) {
            setpassword.setText("");
        }
    }//GEN-LAST:event_setpasswordFocusGained

    private void setpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_setpasswordFocusLost
        if (setpassword.getText().equals("")) {
            setpassword.setText("Password");
        }
    }//GEN-LAST:event_setpasswordFocusLost

    private void confirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmpasswordFocusGained
        if (confirmpassword.getText().equals("Password")) {
            confirmpassword.setText("");
        }
    }//GEN-LAST:event_confirmpasswordFocusGained

    private void confirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmpasswordFocusLost
        if (confirmpassword.getText().equals("")) {
            confirmpassword.setText("Password");
        }
    }//GEN-LAST:event_confirmpasswordFocusLost

    private void codeforcreateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeforcreateFocusGained
        if (codeforcreate.getText().equals("code")) {
            codeforcreate.setText("");
        }
    }//GEN-LAST:event_codeforcreateFocusGained

    private void codeforcreateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeforcreateFocusLost
        if (codeforcreate.getText().equals("")) {
            codeforcreate.setText("code");
        }
    }//GEN-LAST:event_codeforcreateFocusLost
    public void insertuserdata() {
        try {

            try {
                linkwithdatabase = DriverManager.getConnection("jdbc:mysql://localhost:3306/cow_firm_project", "root", "nh12345");
                if (linkwithdatabase != null) {
                    System.out.println("Connected");
                }
                prestat = linkwithdatabase.prepareStatement("insert into user_table values(?,?,?,?)");
                prestat.setString(1, namefeild.getText());//name
                prestat.setString(2, emailfeild.getText());//email
                prestat.setString(3, setpassword.getText());
                prestat.setInt(4, Integer.parseInt(codeforcreate.getText()));

                int n = prestat.executeUpdate();
                if (n > 0) {
                    System.out.println("Insert done");
                } else {
                    System.out.println("Data doesnot insert");
                }

            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                JOptionPane.showMessageDialog(this, "Duplicate entry!");

            }

        } catch (Exception e) {

        } finally {
            try {
                linkwithdatabase.close();
                prestat.close();
            } catch (Exception e) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeforcreate;
    private javax.swing.JLabel codelabel;
    private javax.swing.JTextField confirmpassword;
    private javax.swing.JButton createaccountbtn;
    private javax.swing.JTextField emailfeild;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namefeild;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel passlabel1;
    private javax.swing.JLabel passmatchlabel;
    private javax.swing.JTextField setpassword;
    // End of variables declaration//GEN-END:variables
}
