/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firmdemo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAYEM
 */
public class Updateform extends javax.swing.JFrame {

    Connection linkwithdatabase;
    PreparedStatement prestat;
    DefaultTableModel model;
    Object[] data;
    ResultSet rs;
    int update;

    /**
     * Creates new form DeshBoard
     */
    public Updateform() {
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("Cow no");
        model.addColumn("Stall");
        model.addColumn("Price");
        model.addColumn("Gender");
        model.addColumn("Height");
        model.addColumn("Weight");
        model.addColumn("Type");
        model.addColumn("Dob Month");
        model.addColumn("Dob Month");
        model.addColumn("Description");
        model.addColumn("Supplier");
        model.addColumn("Entry Month");
        model.addColumn("Entry Year");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//not close all window
        showdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buycowform = new javax.swing.JPanel();
        deshlabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deshboardpart = new javax.swing.JPanel();
        deshlabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sellpart = new javax.swing.JPanel();
        deshlabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updatepart = new javax.swing.JPanel();
        deshlabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cowinformation = new javax.swing.JPanel();
        deshlabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        employeespart = new javax.swing.JPanel();
        deshlabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        deletepart = new javax.swing.JPanel();
        deshlabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cownumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cowtype = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        radiomale = new javax.swing.JRadioButton();
        radiofemale = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        heightfeild = new javax.swing.JTextField();
        weightfeid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        updatenbtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        stallno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pricefeild = new javax.swing.JTextField();
        dobmonth = new javax.swing.JComboBox<>();
        dobyear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        cowdescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        showdata = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        supplierfeild = new javax.swing.JComboBox<>();
        todaydate = new javax.swing.JLabel();
        recentlyupdatebtn = new javax.swing.JButton();
        alldatabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\profile.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Rizvi Ahmed");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("active");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\active.png")); // NOI18N
        jLabel4.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        buycowform.setBackground(new java.awt.Color(255, 255, 255));
        buycowform.setForeground(new java.awt.Color(0, 0, 0));
        buycowform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buycowformMouseClicked(evt);
            }
        });

        deshlabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel.setText("Buy");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\cowicon.jpg")); // NOI18N
        jLabel5.setText(" ");

        javax.swing.GroupLayout buycowformLayout = new javax.swing.GroupLayout(buycowform);
        buycowform.setLayout(buycowformLayout);
        buycowformLayout.setHorizontalGroup(
            buycowformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buycowformLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buycowformLayout.setVerticalGroup(
            buycowformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buycowformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buycowformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deshboardpart.setBackground(new java.awt.Color(255, 255, 255));
        deshboardpart.setForeground(new java.awt.Color(0, 0, 0));
        deshboardpart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshboardpartMouseClicked(evt);
            }
        });

        deshlabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel1.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel1.setText("Dashboard");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\deshboard.png")); // NOI18N
        jLabel6.setText(" ");

        javax.swing.GroupLayout deshboardpartLayout = new javax.swing.GroupLayout(deshboardpart);
        deshboardpart.setLayout(deshboardpartLayout);
        deshboardpartLayout.setHorizontalGroup(
            deshboardpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deshboardpartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deshboardpartLayout.setVerticalGroup(
            deshboardpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deshboardpartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deshboardpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel1)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sellpart.setBackground(new java.awt.Color(255, 255, 255));
        sellpart.setForeground(new java.awt.Color(0, 0, 0));
        sellpart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellpartMouseClicked(evt);
            }
        });

        deshlabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel2.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel2.setText("Sell");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\sell.jpg")); // NOI18N
        jLabel7.setText(" ");

        javax.swing.GroupLayout sellpartLayout = new javax.swing.GroupLayout(sellpart);
        sellpart.setLayout(sellpartLayout);
        sellpartLayout.setHorizontalGroup(
            sellpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellpartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sellpartLayout.setVerticalGroup(
            sellpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellpartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellpartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel2)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatepart.setBackground(new java.awt.Color(255, 255, 255));
        updatepart.setForeground(new java.awt.Color(0, 0, 0));
        updatepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatepartMouseClicked(evt);
            }
        });

        deshlabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel4.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel4.setText("Update");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\updateion.png")); // NOI18N
        jLabel9.setText(" ");

        javax.swing.GroupLayout updatepartLayout = new javax.swing.GroupLayout(updatepart);
        updatepart.setLayout(updatepartLayout);
        updatepartLayout.setHorizontalGroup(
            updatepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel4)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        updatepartLayout.setVerticalGroup(
            updatepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel4)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cowinformation.setBackground(new java.awt.Color(255, 255, 255));
        cowinformation.setForeground(new java.awt.Color(0, 0, 0));
        cowinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cowinformationMouseClicked(evt);
            }
        });

        deshlabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel5.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel5.setText("Cow Information");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\buyicon.png")); // NOI18N
        jLabel10.setText(" ");

        javax.swing.GroupLayout cowinformationLayout = new javax.swing.GroupLayout(cowinformation);
        cowinformation.setLayout(cowinformationLayout);
        cowinformationLayout.setHorizontalGroup(
            cowinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cowinformationLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cowinformationLayout.setVerticalGroup(
            cowinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cowinformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cowinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel5)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeespart.setBackground(new java.awt.Color(255, 255, 255));
        employeespart.setForeground(new java.awt.Color(0, 0, 0));
        employeespart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeespartMouseClicked(evt);
            }
        });

        deshlabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel6.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel6.setText("Employees");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\employeeicon.jpg")); // NOI18N
        jLabel11.setText(" ");

        javax.swing.GroupLayout employeespartLayout = new javax.swing.GroupLayout(employeespart);
        employeespart.setLayout(employeespartLayout);
        employeespartLayout.setHorizontalGroup(
            employeespartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeespartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeespartLayout.setVerticalGroup(
            employeespartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeespartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeespartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel6)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deletepart.setBackground(new java.awt.Color(255, 255, 255));
        deletepart.setForeground(new java.awt.Color(0, 0, 0));
        deletepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletepartMouseClicked(evt);
            }
        });

        deshlabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deshlabel3.setForeground(new java.awt.Color(0, 0, 0));
        deshlabel3.setText("Delete");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\deleteicon.jpg")); // NOI18N
        jLabel8.setText(" ");

        javax.swing.GroupLayout deletepartLayout = new javax.swing.GroupLayout(deletepart);
        deletepart.setLayout(deletepartLayout);
        deletepartLayout.setHorizontalGroup(
            deletepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshlabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletepartLayout.setVerticalGroup(
            deletepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshlabel3)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deshboardpart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buycowform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sellpart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cowinformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updatepart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(employeespart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deshboardpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buycowform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cowinformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatepart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletepart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeespart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COW FIRM LOGO");

        logoutbtn.setBackground(new java.awt.Color(51, 153, 255));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Log Out");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\My AsUs\\Documents\\NetBeansProjects\\DAIRYFARMProject\\src\\img\\logouticon.png")); // NOI18N
        jLabel27.setText(" ");

        javax.swing.GroupLayout logoutbtnLayout = new javax.swing.GroupLayout(logoutbtn);
        logoutbtn.setLayout(logoutbtnLayout);
        logoutbtnLayout.setHorizontalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutbtnLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        logoutbtnLayout.setVerticalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1494, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel26.setText("Update Cow Information");

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1377, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Cow Number");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Type");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("Gender");

        buttonGroup1.add(radiomale);
        radiomale.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        radiomale.setText("Male");

        buttonGroup1.add(radiofemale);
        radiofemale.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        radiofemale.setText("Female");
        radiofemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofemaleActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setText("Date of Birth");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText("Height");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("Weight");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText("Description");

        updatenbtn.setBackground(new java.awt.Color(51, 153, 255));
        updatenbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updatenbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatenbtn.setText("Update");
        updatenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenbtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("Stall no");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("Price");

        dobmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        dobyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        cowdescription.setColumns(20);
        cowdescription.setRows(5);
        jScrollPane1.setViewportView(cowdescription);

        showdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        showdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(showdata);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setText("Supplier");

        supplierfeild.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alif group", "Asad Group", "Firoz Group" }));

        todaydate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        todaydate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        recentlyupdatebtn.setBackground(new java.awt.Color(51, 153, 255));
        recentlyupdatebtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recentlyupdatebtn.setForeground(new java.awt.Color(255, 255, 255));
        recentlyupdatebtn.setText("Recent Update");
        recentlyupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recentlyupdatebtnActionPerformed(evt);
            }
        });

        alldatabtn.setBackground(new java.awt.Color(51, 153, 255));
        alldatabtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alldatabtn.setForeground(new java.awt.Color(255, 255, 255));
        alldatabtn.setText("All Information");
        alldatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alldatabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alldatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(recentlyupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(updatenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cownumber, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel17)
                                                    .addComponent(heightfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(stallno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel18)
                                                    .addComponent(weightfeid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(158, 158, 158)))
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(cowtype, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel21)
                                                    .addComponent(pricefeild, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(143, 143, 143)
                                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel16)
                                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                                .addComponent(radiofemale, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                                .addComponent(dobmonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(23, 23, 23)))
                                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(radiomale, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(dobyear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1)
                                        .addGap(158, 158, 158)
                                        .addComponent(supplierfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(511, 511, 511))))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(todaydate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(88, 88, 88))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(todaydate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cownumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stallno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricefeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cowtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightfeid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiofemale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiomale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dobyear)
                                    .addComponent(dobmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentlyupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alldatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buycowformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buycowformMouseClicked
        dispose();
        new buyform().setVisible(true);
    }//GEN-LAST:event_buycowformMouseClicked

    private void deshboardpartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshboardpartMouseClicked
        dispose();
        new DeshBoard().setVisible(true);
    }//GEN-LAST:event_deshboardpartMouseClicked

    private void sellpartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellpartMouseClicked
        dispose();
        new sellform().setVisible(true);
    }//GEN-LAST:event_sellpartMouseClicked

    private void deletepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepartMouseClicked
        dispose();
        new DeleteForm().setVisible(true);
    }//GEN-LAST:event_deletepartMouseClicked

    private void updatepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updatepartMouseClicked

    private void cowinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cowinformationMouseClicked
        dispose();
        new cowinformation().setVisible(true);
    }//GEN-LAST:event_cowinformationMouseClicked

    private void employeespartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeespartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employeespartMouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        dispose();
        new LogIN().setVisible(true);
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void updatenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenbtnActionPerformed
        updatepart();


    }//GEN-LAST:event_updatenbtnActionPerformed
    public void updatepart() {
        try {
            linkwithdatabase = DriverManager.getConnection("jdbc:mysql://localhost:3306/cow_firm_project", "root", "nh12345");
            prestat = linkwithdatabase.prepareStatement("update cowbuy_table set stall_no=?, price=?, gender=?,height=?, weight=?, type=?, dob_month=?,dob_year=?,description=?, supplier=? where cow_number=?");
            String gender = "";
            if (radiomale.isSelected()) {
                gender = "male";
            }
            if (radiofemale.isSelected()) {
                gender = "female";
            }
            prestat.setString(1, stallno.getText());
            prestat.setDouble(2, Double.parseDouble(pricefeild.getText()));
            prestat.setString(3, gender);
            prestat.setDouble(4, Double.parseDouble(heightfeild.getText()));
            prestat.setDouble(5, Double.parseDouble(weightfeid.getText()));
            prestat.setString(6, cowtype.getText());
            prestat.setString(7, dobmonth.getSelectedItem().toString());
            prestat.setString(8, dobyear.getSelectedItem().toString());
            prestat.setString(9, cowdescription.getText());
            prestat.setString(10, supplierfeild.getSelectedItem().toString());
            prestat.setInt(11, Integer.parseInt(cownumber.getText()));
            update = Integer.parseInt(cownumber.getText());
            int n = prestat.executeUpdate();
            if (n > 0) {
                System.out.println("Update Data Sucessfull");
                model.setRowCount(0);
                showdata();
            } else {
                System.out.println("Doesnot Update");
            }

        } catch (Exception e) {
        } finally {
            try {
                linkwithdatabase.close();
                prestat.close();
            } catch (Exception e) {
            }
        }
    }
    private void radiofemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiofemaleActionPerformed

    private void showdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showdataMouseClicked

        cownumber.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 0)));
        stallno.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 1)));
        pricefeild.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 2)));
        if (String.valueOf(model.getValueAt(showdata.getSelectedRow(), 3)).equals("female")) {
            radiofemale.setSelected(true);
        }
        if (String.valueOf(model.getValueAt(showdata.getSelectedRow(), 3)).equals("male")) {
            radiomale.setSelected(true);
        }
        heightfeild.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 4)));
        weightfeid.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 5)));
        cowtype.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 6)));//type
        int i = showdata.getSelectedRow();
        String mont = model.getValueAt(i, 7).toString();
        switch (mont) {
            case "January":
                dobmonth.setSelectedIndex(0);
                break;
            case "February":
                dobmonth.setSelectedIndex(1);
                break;
            case "March":
                dobmonth.setSelectedIndex(2);
                break;
            case "April":
                dobmonth.setSelectedIndex(3);
                break;
            case "May":
                dobmonth.setSelectedIndex(4);
                break;
            case "June":
                dobmonth.setSelectedIndex(5);
                break;
            case "July":
                dobmonth.setSelectedIndex(6);
                break;
            case "August":
                dobmonth.setSelectedIndex(7);
                break;
            case "September":
                dobmonth.setSelectedIndex(8);
                break;
            case "October":
                dobmonth.setSelectedIndex(9);
                break;
            case "November":
                dobmonth.setSelectedIndex(10);
                break;
            case "December":
                dobmonth.setSelectedIndex(11);
                break;
        }
        String yeard = model.getValueAt(i, 8).toString();
        switch (yeard) {
            case "1980":
                dobyear.setSelectedIndex(0);
                break;
            case "1981":
                dobyear.setSelectedIndex(1);
                break;
            case "1982":
                dobyear.setSelectedIndex(2);
                break;
            case "1983":
                dobyear.setSelectedIndex(3);
                break;
            case "1984":
                dobyear.setSelectedIndex(4);
                break;
            case "1985":
                dobyear.setSelectedIndex(5);
                break;
            case "1986":
                dobyear.setSelectedIndex(6);
                break;
            case "1987":
                dobyear.setSelectedIndex(7);
                break;
            case "1988":
                dobyear.setSelectedIndex(8);
                break;
            case "1989":
                dobyear.setSelectedIndex(9);
                break;
            case "1990":
                dobyear.setSelectedIndex(10);
                break;
            case "1991":
                dobyear.setSelectedIndex(11);
                break;
            case "1992":
                dobyear.setSelectedIndex(12);
                break;
            case "1993":
                dobyear.setSelectedIndex(13);
                break;
            case "1994":
                dobyear.setSelectedIndex(14);
                break;
            case "1995":
                dobyear.setSelectedIndex(15);
                break;
            case "1996":
                dobyear.setSelectedIndex(16);
                break;
            case "1997":
                dobyear.setSelectedIndex(17);
                break;
            case "1998":
                dobyear.setSelectedIndex(18);
                break;
            case "1999":
                dobyear.setSelectedIndex(19);
                break;
            case "2000":
                dobyear.setSelectedIndex(20);
                break;
            case "2001":
                dobyear.setSelectedIndex(21);
                break;
            case "2002":
                dobyear.setSelectedIndex(22);
                break;
            case "2003":
                dobyear.setSelectedIndex(23);
                break;
            case "2004":
                dobyear.setSelectedIndex(24);
                break;
            case "2005":
                dobyear.setSelectedIndex(25);
                break;
            case "2006":
                dobyear.setSelectedIndex(26);
                break;
            case "2007":
                dobyear.setSelectedIndex(27);
                break;
            case "2008":
                dobyear.setSelectedIndex(28);
                break;
            case "2009":
                dobyear.setSelectedIndex(29);
                break;
            case "2010":
                dobyear.setSelectedIndex(30);
                break;
            case "2011":
                dobyear.setSelectedIndex(3);
                break;
            case "2012":
                dobyear.setSelectedIndex(32);
                break;
            case "2013":
                dobyear.setSelectedIndex(33);
                break;
            case "2014":
                dobyear.setSelectedIndex(34);
                break;
            case "2015":
                dobyear.setSelectedIndex(35);
                break;
            case "2016":
                dobyear.setSelectedIndex(36);
                break;
            case "2017":
                dobyear.setSelectedIndex(37);
                break;
            case "2018":
                dobyear.setSelectedIndex(38);
                break;
            case "2019":
                dobyear.setSelectedIndex(39);
                break;
            case "2020":
                dobyear.setSelectedIndex(40);
                break;
            case "2021":
                dobyear.setSelectedIndex(41);
                break;

        }
        cowdescription.setText(String.valueOf(model.getValueAt(showdata.getSelectedRow(), 9)));//description
        String supplierp = model.getValueAt(i, 10).toString();
        switch (supplierp) {
            case "Alif group":
                supplierfeild.setSelectedIndex(0);
                break;
            case "Asad Group":
                supplierfeild.setSelectedIndex(1);
                break;
            case "Firoz Group":
                supplierfeild.setSelectedIndex(2);
                break;
        }

    }//GEN-LAST:event_showdataMouseClicked

    private void recentlyupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recentlyupdatebtnActionPerformed
        try {
            linkwithdatabase = DriverManager.getConnection("jdbc:mysql://localhost:3306/cow_firm_project", "root", "nh12345");
            prestat = linkwithdatabase.prepareStatement("select * from cowbuy_table where cow_number=?");
            prestat.setInt(1, update);

            rs = prestat.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                data = new Object[]{rs.getInt(1), rs.getString(2), rs.getDouble(3), rs.getString(4), rs.getDouble(5), rs.getDouble(6), rs.getString(7),
                    rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13)

                };
                model.addRow(data);
                showdata.setModel(model);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_recentlyupdatebtnActionPerformed

    private void alldatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alldatabtnActionPerformed
        showdata();
    }//GEN-LAST:event_alldatabtnActionPerformed
    public void showdata() {
        try {
            linkwithdatabase = DriverManager.getConnection("jdbc:mysql://localhost:3306/cow_firm_project", "root", "nh12345");
            prestat = linkwithdatabase.prepareStatement("select * from cowbuy_table");

            rs = prestat.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                data = new Object[]{rs.getInt(1), rs.getString(2), rs.getDouble(3), rs.getString(4), rs.getDouble(5), rs.getDouble(6), rs.getString(7),
                    rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13)

                };
                model.addRow(data);
                showdata.setModel(model);
            }
        } catch (Exception e) {
        } finally {
            try {
                linkwithdatabase.close();
                prestat.close();
            } catch (Exception e) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alldatabtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buycowform;
    private javax.swing.JTextArea cowdescription;
    private javax.swing.JPanel cowinformation;
    private javax.swing.JTextField cownumber;
    private javax.swing.JTextField cowtype;
    private javax.swing.JPanel deletepart;
    private javax.swing.JPanel deshboardpart;
    private javax.swing.JLabel deshlabel;
    private javax.swing.JLabel deshlabel1;
    private javax.swing.JLabel deshlabel2;
    private javax.swing.JLabel deshlabel3;
    private javax.swing.JLabel deshlabel4;
    private javax.swing.JLabel deshlabel5;
    private javax.swing.JLabel deshlabel6;
    private javax.swing.JComboBox<String> dobmonth;
    private javax.swing.JComboBox<String> dobyear;
    private javax.swing.JPanel employeespart;
    private javax.swing.JTextField heightfeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JTextField pricefeild;
    private javax.swing.JRadioButton radiofemale;
    private javax.swing.JRadioButton radiomale;
    private javax.swing.JButton recentlyupdatebtn;
    private javax.swing.JPanel sellpart;
    private javax.swing.JTable showdata;
    private javax.swing.JTextField stallno;
    private javax.swing.JComboBox<String> supplierfeild;
    private javax.swing.JLabel todaydate;
    private javax.swing.JButton updatenbtn;
    private javax.swing.JPanel updatepart;
    private javax.swing.JTextField weightfeid;
    // End of variables declaration//GEN-END:variables
}
